export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming"
];

export const DENIED_ITEMS = [
  { value: "ice_and_water", label: "Ice and Water Shield" },
  { value: "drip_edge", label: "Drip Edge" },
  { value: "underlayment", label: "Synthetic Underlayment" },
  { value: "starter_strip", label: "Starter Strip" },
  { value: "ridge_vent", label: "Ridge Vent" },
  { value: "pipe_flashing", label: "Pipe Boot/Flashing" },
  { value: "valley_metal", label: "Valley Metal" },
  { value: "step_flashing", label: "Step Flashing" },
  { value: "gutter_apron", label: "Gutter Apron" },
  { value: "ridge_cap", label: "Ridge Cap Shingles" },
  { value: "ventilation", label: "Ventilation System" },
  { value: "deck_replacement", label: "Deck Replacement" },
  { value: "skylight_flashing", label: "Skylight Flashing Kit" },
  { value: "chimney_flashing", label: "Chimney Flashing" },
  { value: "hip_ridge", label: "Hip & Ridge Shingles" }
]; 